version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.3.1

jobs:
  build_mac:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.3.8
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run:
          name: Build 
          command: flutter build macos
      - run: zip -r directory.zip build/macos/Build/Products/Release
      - store_artifacts:
          path: directory.zip
workflows:
  test_and_distribute:
    jobs:
      - build_mac
