version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.3.1

jobs:
  build_mac:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 2.10.3
      - flutter-orb/install_ios_pod
      - run: flutter pub get
      - run: flutter config --enable-mac-desktop
      - run:
          name: Build 
          command: flutter build mac
      - store_artifacts:
          path: ozzie
workflows:
  test_and_distribute:
    jobs:
      - build_mac